# Generated by Django 6.0 on 2026-01-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_bio_user_city_user_district_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_kyc_verified',
            field=models.BooleanField(default=False),
        ),
    ]
