# Generated by Django 6.0 on 2026-03-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio',
            field=models.FileField(blank=True, help_text='Audio file for voice messages', null=True, upload_to='chat_audio/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text Message'), ('voice', 'Voice Message')], default='text', help_text='Type of message: text or voice', max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, help_text='Message content', null=True),
        ),
    ]
