# Generated by Django 6.0 on 2026-04-06 09:59

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_audio_message_message_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='audio',
            field=models.FileField(blank=True, help_text='Audio file for voice messages', null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='chat_audio/%Y/%m/%d/'),
        ),
    ]
