# Generated by Django 6.0 on 2026-02-04 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0003_consultation_meeting_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='notes',
        ),
    ]
