# Generated by Django 6.0 on 2026-02-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0004_remove_consultation_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='meeting_location',
            field=models.CharField(default='', max_length=255),
        ),
    ]
