# Generated by Django 6.0 on 2026-02-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0005_consultation_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
