# Generated by Django 6.0 on 2026-02-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0006_consultation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='meeting_link',
            field=models.CharField(blank=True, help_text='Video meeting link (for video consultations)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='scheduled_date',
            field=models.CharField(blank=True, help_text='Date scheduled by lawyer', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='scheduled_time',
            field=models.CharField(blank=True, help_text='Time scheduled by lawyer', max_length=20, null=True),
        ),
    ]
