# Generated by Django 6.0 on 2026-04-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0007_consultation_meeting_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='is_rated',
            field=models.BooleanField(default=False, help_text='Whether this consultation has been rated by the client'),
        ),
    ]
