# Generated by Django 6.0 on 2026-04-06 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0008_consultation_is_rated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='is_rated',
        ),
    ]
