# Generated by Django 6.0 on 2026-02-01 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_title', models.CharField(help_text='Brief title of the legal case', max_length=200)),
                ('case_category', models.CharField(choices=[('Family Law', 'Family Law'), ('Property Law', 'Property Law'), ('Criminal Law', 'Criminal Law'), ('Corporate Law', 'Corporate Law'), ('Civil Litigation', 'Civil Litigation'), ('Banking & Finance', 'Banking & Finance'), ('Labor Law', 'Labor Law'), ('Immigration Law', 'Immigration Law'), ('Insurance Law', 'Insurance Law'), ('Tort Law', 'Tort Law')], help_text='Category of legal issue', max_length=50)),
                ('case_description', models.TextField(help_text='Detailed description of the legal issue', max_length=2000)),
                ('urgency_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', help_text='Urgency level of the case', max_length=10)),
                ('lawyer_selection', models.CharField(choices=[('specific', 'Specific Lawyer'), ('public', 'Public for All Lawyers')], default='public', help_text='Whether case is public or sent to specific lawyer', max_length=10)),
                ('request_consultation', models.BooleanField(default=False, help_text='Whether client requested a consultation')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('public', 'Public - Open for Lawyers'), ('sent_to_lawyers', 'Sent to Specific Lawyer'), ('proposals_received', 'Proposals Received'), ('accepted', 'Accepted by Lawyer'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='public', help_text='Current status of the case', max_length=20)),
                ('proposal_count', models.IntegerField(default=0, help_text='Number of proposals received from lawyers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When the case was accepted by a lawyer', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the case was marked as completed', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason if case was rejected', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or updates about the case', null=True)),
                ('client', models.ForeignKey(help_text='Client who submitted the case', limit_choices_to={'role': 'Client'}, on_delete=django.db.models.deletion.CASCADE, related_name='cases_submitted', to=settings.AUTH_USER_MODEL)),
                ('lawyer', models.ForeignKey(blank=True, help_text='Lawyer assigned to the case', limit_choices_to={'role': 'Lawyer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_assigned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Uploaded document file', upload_to='case/documents/%Y/%m/%d/')),
                ('file_name', models.CharField(help_text='Original name of the file', max_length=255)),
                ('file_type', models.CharField(help_text='File extension (pdf, jpg, png)', max_length=10)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(help_text='Case this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='case.case')),
            ],
            options={
                'verbose_name': 'Case Document',
                'verbose_name_plural': 'Case Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['client', '-created_at'], name='case_case_client__0600e5_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['lawyer', '-created_at'], name='case_case_lawyer__55c24e_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status'], name='case_case_status_8f2c59_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['case_category'], name='case_case_case_ca_4b0c24_idx'),
        ),
    ]
