# Generated by Django 6.0 on 2026-02-02 09:13

from django.db import migrations


def backfill_accepted_cases(apps, schema_editor):
    """
    For accepted cases without an assigned lawyer, assign the first preferred lawyer.
    This fixes cases that were accepted before the auto-assignment feature was implemented.
    """
    Case = apps.get_model('case', 'Case')
    
    accepted_cases = Case.objects.filter(status='accepted', lawyer__isnull=True)
    updated_count = 0
    
    for case in accepted_cases:
        # Get the first preferred lawyer
        first_preferred = case.preferred_lawyers.first()
        if first_preferred:
            case.lawyer = first_preferred
            case.save()
            updated_count += 1
            print(f"Assigned lawyer {first_preferred.email} to case {case.id}: {case.case_title}")
    
    if updated_count > 0:
        print(f"Successfully backfilled {updated_count} accepted cases with lawyers.")
    else:
        print("No accepted cases needed lawyer assignment.")


def reverse_backfill(apps, schema_editor):
    """
    Reverse operation - not implemented as we can't know which assignments to remove.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_case_preferred_lawyers'),
    ]

    operations = [
        migrations.RunPython(backfill_accepted_cases, reverse_backfill),
    ]
