# Generated by Django 6.0 on 2026-02-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_backfill_accepted_cases_lawyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_number',
            field=models.CharField(blank=True, help_text='Official case number assigned by court', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='court_name',
            field=models.CharField(blank=True, help_text='Name of the court handling this case', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='next_hearing_date',
            field=models.DateField(blank=True, help_text='Date of the next scheduled hearing', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='opposing_party',
            field=models.CharField(blank=True, help_text='Name of the opposing party in the case', max_length=200, null=True),
        ),
    ]
