# Generated by Django 6.0 on 2026-02-03 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0005_casedocument_uploaded_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('case_created', 'Case Created'), ('case_accepted', 'Case Accepted'), ('status_changed', 'Status Changed'), ('document_uploaded', 'Document Uploaded'), ('hearing_scheduled', 'Hearing Scheduled'), ('note_added', 'Note Added'), ('case_updated', 'Case Updated')], help_text='Type of timeline event', max_length=20)),
                ('title', models.CharField(help_text='Title of the event', max_length=200)),
                ('description', models.TextField(help_text='Description of the event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(help_text='Case this timeline event belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='case.case')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this event', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case Timeline',
                'verbose_name_plural': 'Case Timeline',
                'ordering': ['-created_at'],
            },
        ),
    ]
