# Generated by Django 6.0 on 2026-02-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0008_caseappointment_schedule_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_category',
            field=models.CharField(choices=[('Criminal Law', 'Criminal Law'), ('Civil Law', 'Civil Law'), ('Family Law', 'Family Law'), ('Property Law', 'Property Law'), ('Corporate Law', 'Corporate Law'), ('Labor Law', 'Labor Law'), ('Constitutional Law', 'Constitutional Law'), ('Environmental Law', 'Environmental Law'), ('Tax Law', 'Tax Law'), ('Immigration Law', 'Immigration Law')], help_text='Category of legal issue', max_length=50),
        ),
    ]
