# Generated by Django 6.0 on 2026-04-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0009_alter_case_case_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_rated',
            field=models.BooleanField(default=False, help_text='Whether this case has been rated by the client'),
        ),
    ]
