# Generated by Django 6.0 on 2026-04-06 09:59

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0011_alter_caseappointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedocument',
            name='file',
            field=models.FileField(help_text='Uploaded document file', storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='case/documents/%Y/%m/%d/'),
        ),
    ]
