# Generated by Django 6.0 on 2026-01-25 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LawyerKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Female', max_length=10)),
                ('permanent_address', models.TextField()),
                ('current_address', models.TextField()),
                ('bar_council_number', models.CharField(max_length=100, unique=True)),
                ('law_firm_name', models.CharField(blank=True, max_length=255, null=True)),
                ('years_of_experience', models.CharField(max_length=50)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('specializations', models.JSONField(blank=True, default=list)),
                ('availability_days', models.JSONField(blank=True, default=list)),
                ('available_from', models.TimeField(blank=True, null=True)),
                ('available_until', models.TimeField(blank=True, null=True)),
                ('citizenship_front', models.FileField(upload_to='kyc/documents/citizenship/')),
                ('citizenship_back', models.FileField(upload_to='kyc/documents/citizenship/')),
                ('lawyer_license', models.FileField(upload_to='kyc/documents/license/')),
                ('passport_photo', models.FileField(upload_to='kyc/documents/photos/')),
                ('law_degree', models.FileField(upload_to='kyc/documents/degrees/')),
                ('experience_certificate', models.FileField(upload_to='kyc/documents/experience/')),
                ('confirm_accuracy', models.BooleanField(default=False)),
                ('authorize_verification', models.BooleanField(default=False)),
                ('agree_terms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_kyc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lawyer KYC',
                'verbose_name_plural': 'Lawyer KYCs',
                'ordering': ['-created_at'],
            },
        ),
    ]
