# Generated by Django 6.0 on 2026-02-01 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_lawyerreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LawyerReview',
        ),
    ]
