# Generated by Django 6.0 on 2026-03-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_delete_lawyerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerkyc',
            name='esewa_number',
            field=models.CharField(blank=True, help_text='eSewa wallet number for receiving payouts', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lawyerkyc',
            name='khalti_number',
            field=models.CharField(blank=True, help_text='Khalti wallet number for receiving payouts', max_length=20, null=True),
        ),
    ]
