# Generated by Django 6.0 on 2026-04-06 09:59

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0004_lawyerkyc_esewa_number_lawyerkyc_khalti_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyerkyc',
            name='citizenship_back',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='kyc/documents/citizenship/'),
        ),
        migrations.AlterField(
            model_name='lawyerkyc',
            name='citizenship_front',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='kyc/documents/citizenship/'),
        ),
        migrations.AlterField(
            model_name='lawyerkyc',
            name='experience_certificate',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='kyc/documents/experience/'),
        ),
        migrations.AlterField(
            model_name='lawyerkyc',
            name='law_degree',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='kyc/documents/degrees/'),
        ),
        migrations.AlterField(
            model_name='lawyerkyc',
            name='lawyer_license',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='kyc/documents/license/'),
        ),
        migrations.AlterField(
            model_name='lawyerkyc',
            name='passport_photo',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='kyc/documents/photos/'),
        ),
    ]
