# Generated by Django 6.0 on 2026-02-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('in_hand', 'In Hand')], default='pending', max_length=20),
        ),
    ]
