# Generated by Django 6.0 on 2026-02-27 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short title of the notification', max_length=255)),
                ('message', models.TextField(help_text='Full notification message')),
                ('notif_type', models.CharField(choices=[('case', 'Case Update'), ('appointment', 'Appointment'), ('message', 'Message'), ('payment', 'Payment'), ('alert', 'Alert'), ('system', 'System')], default='system', help_text='Category of the notification', max_length=20)),
                ('is_read', models.BooleanField(default=False, help_text='Whether the user has read this notification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User this notification belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_c4d245_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_543da6_idx')],
            },
        ),
    ]
