# Generated by Django 6.0 on 2026-02-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, help_text='Frontend route to navigate to when notification is clicked', max_length=255, null=True),
        ),
    ]
