# Generated by Django 6.0 on 2026-02-04 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case', '0006_casetimeline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_text', models.TextField(help_text="Lawyer's proposal text explaining their experience and approach", max_length=2000)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted by Client'), ('rejected', 'Rejected by Client'), ('withdrawn', 'Withdrawn by Lawyer')], default='pending', help_text='Current status of the proposal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the proposal was reviewed by the client', null=True)),
                ('client_feedback', models.TextField(blank=True, help_text='Feedback from client if rejected', null=True)),
                ('case', models.ForeignKey(help_text='Case this proposal is for', on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='case.case')),
                ('lawyer', models.ForeignKey(help_text='Lawyer who submitted the proposal', limit_choices_to={'role': 'Lawyer'}, on_delete=django.db.models.deletion.CASCADE, related_name='proposals_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proposal',
                'verbose_name_plural': 'Proposals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['case', '-created_at'], name='proposal_pr_case_id_908804_idx'), models.Index(fields=['lawyer', '-created_at'], name='proposal_pr_lawyer__7ac4a0_idx'), models.Index(fields=['status'], name='proposal_pr_status_38301f_idx')],
                'unique_together': {('case', 'lawyer')},
            },
        ),
    ]
