# Generated by Django 6.0 on 2026-02-04 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proposal',
            unique_together=set(),
        ),
    ]
