# Generated by Django 6.0 on 2026-02-04 06:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0006_casetimeline'),
        ('proposal', '0002_alter_proposal_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proposal',
            unique_together={('case', 'lawyer')},
        ),
    ]
