# Generated by Django 6.0 on 2026-04-06 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_payment_status'),
        ('case', '0010_case_is_rated'),
        ('review', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('client', 'lawyer')},
        ),
        migrations.AddField(
            model_name='review',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='appointment.appointment'),
        ),
        migrations.AddField(
            model_name='review',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='case.case'),
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_verified_consultation',
        ),
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
    ]
