# Generated by Django 6.0 on 2026-01-25 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LawyerKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IdentityDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship_front', models.FileField(upload_to='kyc/documents/')),
                ('citizenship_back', models.FileField(upload_to='kyc/documents/')),
                ('lawyer_license', models.FileField(upload_to='kyc/documents/')),
                ('passport_photo', models.FileField(upload_to='kyc/documents/')),
                ('law_degree', models.FileField(upload_to='kyc/documents/')),
                ('experience_certificate', models.FileField(upload_to='kyc/documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kyc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity_documents', to='kyc.lawyerkyc')),
            ],
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm_accuracy', models.BooleanField(default=False)),
                ('authorize_verification', models.BooleanField(default=False)),
                ('agree_terms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kyc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='declaration', to='kyc.lawyerkyc')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('permanent_address', models.TextField()),
                ('current_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kyc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to='kyc.lawyerkyc')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_council_number', models.CharField(max_length=100, unique=True)),
                ('law_firm_name', models.CharField(blank=True, max_length=255, null=True)),
                ('years_of_experience', models.CharField(max_length=50)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('specializations', models.JSONField(default=list)),
                ('availability_days', models.JSONField(default=list)),
                ('available_from', models.TimeField()),
                ('available_until', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kyc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_info', to='kyc.lawyerkyc')),
            ],
        ),
    ]
