# Generated by Django 6.0 on 2026-03-06 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_lawyer_payment_lawyer_earning_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payout_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', help_text='Whether the lawyer has been paid their earning.', max_length=20),
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount paid out to the lawyer.', max_digits=10)),
                ('reference_number', models.CharField(blank=True, help_text='Bank transfer or eSewa reference number.', max_length=255, null=True)),
                ('payment_method', models.CharField(blank=True, help_text='Method used for payout (e.g., bank transfer, eSewa).', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this payout.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL)),
                ('payments', models.ManyToManyField(related_name='payouts', to='payment.payment')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
