# Generated by Django 6.0 on 2026-03-27 09:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0009_alter_case_case_category'),
        ('payment', '0003_payment_payout_status_payout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CasePaymentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proposed_amount', models.DecimalField(decimal_places=2, help_text='Initial amount proposed by lawyer.', max_digits=10)),
                ('current_agreed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Currently agreed amount (may be different from proposed).', max_digits=10, null=True)),
                ('client_counter_offer', models.DecimalField(blank=True, decimal_places=2, help_text='Latest counter-offer from client.', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('negotiating', 'Negotiating'), ('agreed', 'Agreed'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='pending', help_text='Current status of payment request.', max_length=20)),
                ('rejection_count', models.IntegerField(default=0, help_text='Number of times client rejected the offer.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Payment request expires 30 days after creation.', null=True)),
                ('responded_at', models.DateTimeField(blank=True, help_text='When client first responded to payment request.', null=True)),
                ('agreed_at', models.DateTimeField(blank=True, help_text='When both parties agreed on amount.', null=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='When payment was completed.', null=True)),
                ('description', models.TextField(blank=True, help_text="Lawyer's justification for the amount.", null=True)),
                ('case', models.OneToOneField(help_text='The case for which payment is being requested.', on_delete=django.db.models.deletion.CASCADE, related_name='payment_request', to='case.case')),
                ('lawyer', models.ForeignKey(help_text='The lawyer requesting payment.', on_delete=django.db.models.deletion.CASCADE, related_name='case_payment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='payment_cas_status_a5667c_idx'), models.Index(fields=['lawyer', 'status'], name='payment_cas_lawyer__6f10cb_idx'), models.Index(fields=['expires_at'], name='payment_cas_expires_d549b4_idx')],
            },
        ),
    ]
