# Generated by Django 6.0 on 2026-03-27 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_payment_status'),
        ('payment', '0004_casepaymentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='case_payment_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payment.casepaymentrequest'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='appointment.appointment'),
        ),
    ]
