# Generated by Django 6.0 on 2026-03-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_payment_case_payment_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casepaymentrequest',
            name='client_counter_offer',
        ),
        migrations.RemoveField(
            model_name='casepaymentrequest',
            name='rejection_count',
        ),
        migrations.AlterField(
            model_name='casepaymentrequest',
            name='current_agreed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The final amount agreed by both parties.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casepaymentrequest',
            name='proposed_amount',
            field=models.DecimalField(decimal_places=2, help_text='The amount requested by the lawyer.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='casepaymentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('agreed', 'Agreed'), ('paid', 'Paid')], default='pending', help_text='Current status of payment request.', max_length=20),
        ),
    ]
